#@data/values
---
port: 3000

env:
  - name: TZ
    value: America/Sao_Paulo

ingress:
  enable: true
  type: traefik

  tls:
    enable: true
    domain: forattini.app
    letsencrypt:
      enable: true
